[build]
  command = "pip install -r requirements.txt"

[dev]
  command = "set FLASK_APP=app.main:app && set FLASK_ENV=development && flask run"

[production] # Or use [context.production.run] if preferred
  command = "gunicorn --bind 0.0.0.0:$PORT app.main:app" 